### ISSUE TITLE
16 bit push results in 64 bit push if bit 15 is set

### ISSUE THREAD

**Issue by brad-kelly** [herumi/xbyak#103]
If bit 15 is set in the data `push(word, value)` will use a pushq instead of pushw.

do a `push(word, 0xFFFF);`  // should be 16 bit signed push

The code for push is:
```
	void push(const AddressFrame& af, uint32 imm)
	{
		if (af.bit_ == 8 && inner::IsInDisp8(imm)) {
			db(0x6A); db(imm);
		} else if (af.bit_ == 16 && isInDisp16(imm)) {
			db(0x66); db(0x68); dw(imm);
		} else {
			db(0x68); dd(imm);
		}
	}

```
The code above is using:
`
	bool isInDisp16(uint32 x) const { return 0xFFFF8000 <= x || x <= 0x7FFF; }
`
to determine if the value can fit in 16 bits.  But displacements are signed quantities, while the value of a push is unsigned.  So the code above results in any push instruction that sets bit 15 to use a 64 bit push when I 16 bit would have done.

I believe the code for push should do:
```
		if (af.bit_ == 8 && imm <= 0xFF) {
			db(0x6A); db(imm);
		} else if (af.bit_ == 16 && imm <= 0xFFFF) {
```

**Comment by brad-kelly** [comment]
Right now I'm seeing xbyak produce `68FFFF0000`  (no 66 prefix) which ends up being a pushq.  I'd expect it to produce `6668FFFF`.  There's nothing illegal about `push(word, 0xffff)` because it fits fine in 16 bits - my problem is that it changes it to a 64 bit pushq (no 66 prefix)

Going forward, even if the data does not fit in the destination format, I think changing the explicitly declared push size seems wrong.  If the data does not fit in the destination size I would expect one of two things to happen.  Either:
1. truncate the data to fit the explicitly stated size, or
2. throw an exception.

either would be acceptable.

**Comment by herumi** [comment]
I see.
I supposed that that `push(word, -1)` was used for `6668FFFF` because imm16 is between -32768 and 32767 and it will be converted to uint32_t.
I'll modify the current behavior.

**Comment by herumi** [comment]
How about https://github.com/herumi/xbyak/commit/be492be1a4979617d323fb572958d4478edfbb51#diff-aafd8dc5d7c50d5243799e143e40ec6e ?

**Comment by brad-kelly** [comment]
Looks perfect.

**Comment by herumi** [comment]
Thank you for checking. By the way, could you tell me what situation did you need the `push word`?
