### ISSUE TITLE
Possibility of constexpr in the interface?

### ISSUE THREAD

**Issue by lioncash** [herumi/xbyak#104]
Hi,

This is an issue asking if there was any plan in the future for the interface (or at least the constructors of many of the register classes) to be constexpr.

This way things like file-scope register declarations can be made without potentially needing to have a runtime static constructor on program execution, eliminating a bit of code that needs to be run before main() can be executed. For example, in one of the project we maintain, we have the [following](https://github.com/yuzu-emu/yuzu/blob/master/src/video_core/macro/macro_jit_x64.cpp#L17)

It would be nice to be able to mark these as constexpr so the compiler can remove static constructors for these variables, but due to the API lacking constexpr we cannot do this. 

It's not a terribly huge deal, but it would be nice to be able to do such a thing (as it would also allow some of the machinery around the registers to potentially be constexpr as well). Is this a possible thing that could be added to the interface in the future?

**Comment by herumi** [comment]
Thank you for your proposal. I'll consider the idea.

**Comment by herumi** [comment]
I updated xbyak at https://github.com/herumi/xbyak/commit/c306b8e5786eeeb87b8925a8af5c3bf057ff5a90 . It requires C++ 14 or later.
How about it?

**Comment by lioncash** [comment]
This is great! Thanks for making these changes to the interface 😃

**Comment by herumi** [comment]
Thank you for the verification.
