### ISSUE TITLE
Why addressing do not support scale * index form.

### ISSUE THREAD

**Issue by CaoZhongZ** [herumi/xbyak#111]
Any reason why xbyak do not support form like:
```
lea(r9, ptr[rdi + 4 * r15]);
```
And must using
```
lea(r9, ptr[rdi + r15 * 4]);
```

I'm transforming some assembly to xbyak jit, it is painful to adjust too many order of scale and index.

**Comment by herumi** [comment]
>Any reason why xbyak do not support form like:

Because nobody did want the feature.

> it is painful to adjust too many order of scale and index.

I see. I'll support the feature.

**Comment by CaoZhongZ** [comment]
Thanks for the reply! I was just afraid that there might be consequence if overload operator* for it, if there isn't, support the other order would make transform script easier. 😄

**Comment by herumi** [comment]
I've supported it.
https://github.com/herumi/xbyak/commit/1f119a04ac5d6b5555a16af4398dcec47adaab8e

**Comment by CaoZhongZ** [comment]
Thanks!
