### ISSUE TITLE
How is this library name pronounced?

### ISSUE THREAD

**Issue by Adonai** [herumi/xbyak#116]
xbyak is a bit strange word, could you please add English pronunciation rules using [International Phonetic Alphabet](https://en.wikipedia.org/wiki/Help:IPA/English)?

Trying to avoid SeQueL vs esSQueL issues in future.

**Comment by kawakami-k** [comment]
In the following link, Google translate pronounces Xbyak.
https://translate.google.com/?hl=ja&sl=ja&tl=en&text=kaibyaku

Xbyak is based on a Japanese word written in kanji (Chinese characters). It meanings is "the beginning of the world", "exploring the unexplored", etc.

**Comment by herumi** [comment]
It's "kəi-bja-k" (I'm not sure the correct spelling by IPA).
As @kawakami-k wrote, the origin of "xbyak" is a Japanese word [開闢](https://translate.google.com/?hl=ja&sl=ja&tl=en&text=%E9%96%8B%E9%97%A2&op=translate).

**Comment by Adonai** [comment]
Thank you!
