### ISSUE TITLE
AVX512_FP16

### ISSUE THREAD

**Issue by Wunkolo** [herumi/xbyak#118]
Intel has released the 1.0 specification for the upcoming AVX512-FP16 extension, complete with instruction encodings. There is no hardware out yet(planned for SapphireRapids and AlderLake), but I wanted to create this issue to track interest in xbyak supporting this extension once it comes out.

[1.0 Specification](https://software.intel.com/content/www/us/en/develop/download/intel-avx512-fp16-architecture-specification.html)

![image](https://user-images.githubusercontent.com/644247/124828876-b4372500-df2c-11eb-8719-47cd675d7dc4.png)
![image](https://user-images.githubusercontent.com/644247/124828997-dfba0f80-df2c-11eb-9800-3c5ccf849af7.png)

[Intel Software Development Emulator does not yet support this feature yet](https://software.intel.com/content/www/us/en/develop/articles/intel-software-development-emulator-release-notes.html)

**Comment by herumi** [comment]
Okay, I'll check it later.

**Comment by Wunkolo** [comment]
An update, [Intel's Software Development Emulator now supports AVX512-FP16](https://software.intel.com/content/www/us/en/develop/articles/intel-software-development-emulator.html).

**Comment by herumi** [comment]
[xbyak 6.00](https://github.com/herumi/xbyak/releases/tag/v6.00) supports AVX512-FP16.

**Comment by Wunkolo** [comment]
Thank you so very much!!
