### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhoutianzi666** [herumi/xbyak#123]
terminate called after throwing an instance of 'Xbyak::Error'
  what():  opmask is already set
Aborted (core dumped)

**Comment by herumi** [comment]
What OS, CPU, compiler and code do you use?

**Comment by zhoutianzi666** [comment]
> What OS, CPU, compiler and code do you use?

I am using xbyak to calculate matrix multiplication, but other parts call the MKL library. When the program runs to the MKL library, an error will be reported

**Comment by herumi** [comment]
The error occurs from a code like `vaddps(xmm1|k2|k3,xmm2, xmm3);` because it is forbitten.
I think that there is such a code in your source and please verify it.
