### ISSUE TITLE
24 bytes of shadow space instead of 32 bytes on x64?

### ISSUE THREAD

**Issue by mVento3** [herumi/xbyak#125]
I have noticed something weird, when calling function address with more than 4 arguments. Instead of `mov(qword[rsp + 32], 10ull);` with 32 bytes of shadow space, I need to add 24 bytes of shadow space, because if not, then the fifth argument is not passed in, and the value is in sixth argument. It is normal?

Windows 10 build 19042.1237
MSVC 19.28.29915 for x64

**Comment by herumi** [comment]
Though I don't understand your intention, shadow space is always 32 bytes.
https://retroscience.net/x64-assembly.html#fast-call-procedure-shadow-space-home-space

**Comment by mVento3** [comment]
The fifth argument should be on rsp + 32, and sixth rsp + 40, right? But while using Xbyak, I cant put fifth argument on rsp + 32, because then it is sixth argument, I need to put it on rsp + 24 instead, and sixth on rsp + 32. When I will come home, I will post some code.

**Comment by herumi** [comment]
I can't understand your code.
Do you want to generate a code calling a function having n-arguments?
The sample code does not call a generated function. Is it okay?

**Comment by mVento3** [comment]
No, it is working fine, but my question is why I need to use 24 bytes of home space instead of 32. My code is simple, I am pushing n-arguments and I am calling a function with those arguments.

**Comment by herumi** [comment]
It's not a problem with Xbyak.

If you remove `***` in the followings, will it go well?
```
  push(rbp); // ***
  mov(rbp, rsp); // ***
  ...
  mov(rsp, rbp); // ***
  pop(rbp); // ***
```

**Comment by mVento3** [comment]
It is the same, no difference. Still using 24 bytes of shadow space.

**Comment by herumi** [comment]
In your code,

```
push(rbp);
mov(rbp, rsp);
sub(rsp, 24); // I know it should be 32, but it is not working, need to be 24, idk why
```
Then, I told the code
```
// push(rbp);
// mov(rbp, rsp);
sub(rsp, 32);
```
is equivalent with the above.

see https://stackoverflow.com/questions/64542080/why-isnt-msvc-allocating-a-32-byte-shadow-space-in-the-generated-assembly-code

>Subtracting 24 from RSP here doesn't have anything to do with shadow space.

**Comment by mVento3** [comment]
I just realized I did not understand my own code... Everything is working fine, when fifth argument is pushed, the `m_uiIndex` has value 6, not 5, so it is applying the additional 8 bytes to 24... Sorry about that 😅Have a good day/evening
