### ISSUE TITLE
Broken test suite on x86 (IA-32)

### ISSUE THREAD

**Issue by Tachi107** [herumi/xbyak#142]
As mentioned in https://github.com/herumi/xbyak/commit/6de93fb8843d471137637c644ce48947a8ad23cc#r68557045, commits 6de93fb8843d471137637c644ce48947a8ad23cc and 2bc8fcbd38a736727732489693d097f6c7fa56b8 introduced the usage of `xm16` in the code, but that symbol is only defined when `XBYAK64` is defined, i.e. on x86-64.

This causes test failures on x86, as you can see [here](https://salsa.debian.org/debian/xbyak/-/jobs/2555994#L1029).

I haven't submitted a PR as I don't know how you'd prefer to solve this :)

**Comment by herumi** [comment]
Thank you for pointing that out.
I forgot that the test was in 64-bit mode only. I've fixed it.

**Comment by Tachi107** [comment]
Thanks for the rapid fix!
