### ISSUE TITLE
WAITPKG

### ISSUE THREAD

**Issue by Wunkolo** [herumi/xbyak#143]
Creating this issue to track interest in the `WAITPKG` instructions, introduced since Tremont(also found in sapphire rapids and alderlake)
The `WAITPKG` cpuid flag indicates the availability of three new instructions `umonitor`, `umwait`, `tpause`.

![image](https://user-images.githubusercontent.com/644247/161432173-49b952fa-296e-41c8-8741-a4e1cbbaeff5.png)
![image](https://user-images.githubusercontent.com/644247/161432263-f03693a9-7c98-4868-ba60-4ce9fa22d1c8.png)
![image](https://user-images.githubusercontent.com/644247/161432294-1aba02c6-d285-4825-b6a8-43fd7db4491b.png)
![image](https://user-images.githubusercontent.com/644247/161432313-fa5ad956-21eb-4036-928b-e4737dca2459.png)

**Comment by herumi** [comment]
Okay, I've added them at https://github.com/herumi/xbyak/tree/dev .

**Comment by Wunkolo** [comment]
Thank you very much!
