### ISSUE TITLE
Cpu::has() check is inconsistent

### ISSUE THREAD

**Issue by nivas-x86** [herumi/xbyak#148]
The Cpu::has() parallel check seems to broken. 

Below code on Haswell machine prints "WRONG" . (The commit https://github.com/herumi/xbyak/commit/3ea8e45d33bbe22b4130d1bf01edc91b8aadf7fa prints "OK")

```cpp
#include <stdio.h>
#include "xbyak/xbyak_util.h"

using namespace Xbyak::util;

int main() {
    Cpu hsw;
    if ((hsw.has(Cpu::tAVX2) && hsw.has(Cpu::tAVX512F)) == hsw.has(Cpu::tAVX2 | Cpu::tAVX512F)) {
        printf("OK\n");
        return 0;
    } else {
        printf("WRONG\n");
        return -1;
    }
}
```

**Comment by herumi** [comment]
Sorry for the incompleteness.
Is [this patch](https://github.com/herumi/xbyak/commit/b48a7bb1b72ff4bf0c8363985ab7c3cb3c68ae7b) okay?

**Comment by nivas-x86** [comment]
No problem. 
Thank you for the quick fix, it works fine now.

**Comment by herumi** [comment]
Thank you for the quick check. I've pushed it into the master branch.
