### ISSUE TITLE
The version number went backwards: 6.052 -> 6.06

### ISSUE THREAD

**Issue by yurivict** [herumi/xbyak#151]
The FreeBSD version comparison says that it went backwards:
```
$ pkg version -t 6.052 6.06
>
```

Maybe using the standard semantic versioning system X.Y.Z is better?

**Comment by yurivict** [comment]
yes.

**Comment by herumi** [comment]
Okay, I'll apply the format in the next version.

**Comment by herumi** [comment]
cf. https://github.com/herumi/xbyak/commit/553246c164c300723ad614d1a83a7c7e10fc60d8

**Comment by yurivict** [comment]
Maybe you can make a new release with an increasing version number?

FreeBSD system and people keep sending me notifications about version number going backwards.

**Comment by herumi** [comment]
Is it okay to release version 6.60?

**Comment by yurivict** [comment]
Yes.

**Comment by herumi** [comment]
I've released it.

**Comment by yurivict** [comment]
Thanks!

**Comment by Tachi107** [comment]
Thank you for this report and the corresponding change! I observed the same behaviour in Debian, and I avoided packaging versions that were "less" than the previous. Thanks again :D
