### ISSUE TITLE
movzx eax, ah

### ISSUE THREAD

**Issue by merryhime** [herumi/xbyak#155]
For the following code: 
```
    movzx(eax, ah);
```

I expect the following to be emitted: 
```
    0F B6 C4    ; movzx eax, ah
```

Unfortunately I get a `bad combination` error instead.

**Comment by herumi** [comment]
Thank you for the report.
I don't remember why, but I was restricting it.
I removed it at https://github.com/herumi/xbyak/commit/d224701f4a19704211879bae0eb80070d22b6bb6 .
Would you try it?

**Comment by herumi** [comment]
I've merged it into the master branch.

**Comment by merryhime** [comment]
Thank you for the fix, and apologies for the delay in response. Verified.
