### ISSUE TITLE
"invalid token at start of a preprocessor expression"

### ISSUE THREAD

**Issue by Arthurfogo7** [herumi/xbyak#157]
I'm trying to compile this, but this error always occurs when trying to do so, what do I do to fix that?

![image](https://user-images.githubusercontent.com/85951083/184280104-dd9014ad-26ae-42dd-95bd-10f3b48aee0c.png)

**Comment by herumi** [comment]
What compiler, version, and OS do you use?

**Comment by Arthurfogo7** [comment]
Visual Studio 2019, Windows 10. I have clang cl, I thought that should be enough. What causes this error?

**Comment by herumi** [comment]
I test the following command, and it runs well on both Visual Studio 2019 and 2022.
Could you try it?

```
>cd xbyak/sample
xbyak\sample>clang-cl /EHa -I .. test_util.cpp && test_util
64bit
vendor intel
 mmx mmx2 cmov sse sse2 sse3  ...
```

Visual Studio 2022
```
clang-cl -v
clang version 14.0.5
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin
```

Visual Studio 2019
```
clang-cl -v
clang version 12.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\x64\bin
```

**Comment by Arthurfogo7** [comment]
When I updated to Visual Studio 2022, it worked. It seems that clang 12.0.0 from Visual Studio 2019 doesn't work for xbyak.

**Comment by herumi** [comment]
as I wrote at https://github.com/herumi/xbyak/issues/157#issuecomment-1212838653, clang-cl on Visual Studio 2019 runs well on my environment.

What result of `clang-cl /EHa -I .. test_util.cpp` is?
