### ISSUE TITLE
x64 addressing problem

### ISSUE THREAD

**Issue by zxmarcos** [herumi/xbyak#16]
How can I move a variable value to register on x64?
I am trying to do:

uint64_t var;
mov(rax, ptr[&var]);

I got error message: offset is too big

I tried:
mov(rax, qword[(size_t)&var]);
But it moves the var address as immediate value to rax.

How can I write: mov rax, qword[var]?

**Comment by herumi** [comment]
x64 addressing support only 32-bit offset, so write as the following:
mov(rax, (size_t)&var);
mov(rax, ptr [rax]);

**Comment by herumi** [comment]
Intel x64 addressing supports only 32-bit offset.
So you should write as the folloing:
uint64_t var;
mov(rax, (size_t)&var);
mov(rax, ptr [rax]);
