### ISSUE TITLE
Question on error stickyness

### ISSUE THREAD

**Issue by mgouicem** [herumi/xbyak#163]
Hi @herumi , I have a quick question about error statuses stickyness.

I see that inside the LabelManager constructor, we call reset which in turn resets the error status [here](https://github.com/herumi/xbyak/blob/master/xbyak/xbyak.h#L1488).

Can you share the rational for resetting this error status?
When exceptions are disabled this breaks the stickyness or error codes. Thanks.

**Comment by herumi** [comment]
Thank you for the question.
It is better to move ClearError() into the constructor of CodeGenerator.

**Comment by herumi** [comment]
https://github.com/herumi/xbyak/commit/5e27eddaeb4f40076fb32857982af1955d2b1a16

**Comment by mgouicem** [comment]
Thanks for the clarification and fix!
