### ISSUE TITLE
Please use ${CXX} instead of hardcoding g++ because in different systems C++ compiler has different executable names

### ISSUE THREAD

**Issue by yurivict** [herumi/xbyak#166]
Additionally, when the compilation command fails because the compiler is non-existent the script continues and prints bogus messages. You probably want to add ```set -x``` to make scripts stop on errors.

**Comment by herumi** [comment]
Thank you for the advice.
I've changed the Makefile.
https://github.com/herumi/xbyak/commit/6989aea9460557bf0d4aec4681ea73f0a05cfd96

**Comment by yurivict** [comment]
Thank you.
