### ISSUE TITLE
RISC-V ISA support

### ISSUE THREAD

**Issue by pazamelin** [herumi/xbyak#170]
Hello!

Would you consider adding support for RISC-V ISA here or should it be done in a separate project like [xbyak_aarch64](https://github.com/fujitsu/xbyak_aarch64)?

Thanks,

**Comment by herumi** [comment]
Okay, I know very little about RISC-V but I will look into it and try it.

**Comment by herumi** [comment]
I've started to develop a xbyak for RISC-V.
https://github.com/herumi/xbyak_riscv
