### ISSUE TITLE
aligned allocation requests should be rounded up to page size

### ISSUE THREAD

**Issue by alk** [herumi/xbyak#174]
I.e. when _aligned_malloc/posix_memalign is used. Because while it gives you memory which starts at page boundary, it may actually end in not at page boundary. Then you when do mprotect/VirtualProtect you'll be occasionally changing permission for memory that doesn't belong to your allocation.

I do see that yout mmap allocator does the alignment.

(Apologies if I misunderstood anything from my 10 minute journey in your code base; say if sizes are already aligned)

Filing this off here (which is likely what happens due to lack of alignment): https://github.com/gperftools/gperftools/issues/1157

**Comment by herumi** [comment]
Thanks for the advice.
I knew this problem "might" happen, but since I don't use a non-4096 byte environment, I left it alone. I will try to figure out how to deal with it.

**Comment by herumi** [comment]
v6.71 supports it.
