### ISSUE TITLE
AMD MONITORX instructions support

### ISSUE THREAD

**Issue by Morph1984** [herumi/xbyak#175]
This is similar to UMWAIT, UMONITOR provided in the Intel WAITPKG instructions, useful for power-efficient spinlocks.

https://www.amd.com/system/files/TechDocs/24594.pdf

![image](https://github.com/herumi/xbyak/assets/39850852/5fb0fc05-d789-4fba-ba7c-5ef4f9384663)
![image](https://github.com/herumi/xbyak/assets/39850852/c848b705-be97-4096-8f42-195915504ec9)
![image](https://github.com/herumi/xbyak/assets/39850852/0208fb85-a0f5-43d8-8b16-ce8d38fd82e3)
![image](https://github.com/herumi/xbyak/assets/39850852/ab7a9b34-be10-442b-96b3-9b18acd0254d)
![image](https://github.com/herumi/xbyak/assets/39850852/3d110837-66ac-45e1-9d82-88389da4f080)

**Comment by herumi** [comment]
Xbyak already supports monitorx and mwaitx instructions.

**Comment by Morph1984** [comment]
I apologize for not checking, I will close this issue.
Thank you for all your work in xbyak
