### ISSUE TITLE
Support for Intel APX and AVX10

### ISSUE THREAD

**Issue by StrikerX3** [herumi/xbyak#176]
See [here](https://www.intel.com/content/www/us/en/developer/articles/technical/advanced-performance-extensions-apx.html) for details.

Intel APX doubles the number of GPRs and adds instruction encodings to existing x86 instructions to support the new GPRs as well as a separate destination register for old ALU instructions, among more new features. AVX10 essentially consolidates vector instruction sets, including AVX-512, and allows AVX-512 instructions to be used with 256-bit wide YMM registers.

**Comment by herumi** [comment]
I read the documents, too. APX and AVX10 are topics independent of each other, and they require huge modification.
There are no tools yet, so we can't check my implementation if I implement it.
I will respond when I get more information.

**Comment by Wunkolo** [comment]
Intel Software Development Emulator now supports Intel APX and AMX, to verify an implementation.
https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html

**Comment by herumi** [comment]
Yes, I already know that. It will just take a very long time to support them.

**Comment by herumi** [comment]
@StrikerX3 @Wunkolo 
See https://github.com/herumi/xbyak/issues/176 for progress.
