### ISSUE TITLE
RIP-relative addressing with labels

### ISSUE THREAD

**Issue by whyisthisfieldhere** [herumi/xbyak#18]
Hi.

I noticed that while I can create a RIP-relative address via ptr[rip + <int>], this doesn't allow me to easily create RIP-relative addresses pointing to other locations in the code buffer (e.g. to a bunch of data I will put right after the code).

I would want to be able to write things like:
> Label myLabel;
> padd (xmm0, ptr[rip + myLabel]);
> <...>
> L (myLabel);
> db (myData, 16);

I ended up changing xbyak to support this. In case it helps, I've uploaded the result here: 
http://codepad.org/QTKeKx3T
(WARNING: It's only tested for my specific usecase; I could upload this as Pull Request if you want)

Thanks.

**Comment by herumi** [comment]
Thank you for your code. I'll check it.

**Comment by herumi** [comment]
Thank you for your excellent code.
I merged and modifed your code a little.
https://github.com/herumi/xbyak/commit/2158b5387167b921106732d3be2f1c2e9bbd2727

You can write as the following code.
Is this your desired specification?
```
Label label1, label2;
jmp("@f");
L(label1);
  db(a0, 4);
  db(a1, 4);
L("@@");
  mov(eax, ptr [rip + label1]);       // a0
  add(eax, ptr [rip + label1+4]);     // a1
  add(eax, ptr [rip + label2-8+2+6]); // b0
  add(eax, ptr [rip + 16+label2-12]); // b1
  ret();
L(label2);
  db(b0, 4);
  db(b1, 4);
```

**Comment by whyisthisfieldhere** [comment]
Thank you very much for merging and improving my changes, this is indeed the specification I was hoping for.

However, testing it on my project, I found a bug with the modified changes:

The following code:
pshufb (xmm2, ptr[rip+myLabel]);
Generates the following instruction:
pshufb xmm0, <correct rip-based offset>
(The bug is that xmm2 became xmm0)

This happens because the new code always outputs 0x05 for rip-relative addresses with a label, even if updateRegField was called on the address.

**Comment by herumi** [comment]
I'm sorry. I fixed it. https://github.com/herumi/xbyak/commit/c81d6d83111a2b78f129bb5760a5ca56841e8d95
Could you try it again?

**Comment by whyisthisfieldhere** [comment]
Thanks, herumi!
I've tested the updated branch and it works great with my project.

**Comment by herumi** [comment]
Thank you for the confirmation.
