### ISSUE TITLE
Reverting c7c1eac and 9f53572

### ISSUE THREAD

**Issue by Tachi107** [herumi/xbyak#189]
Hi!

After the introduction of commits c7c1eac070851068d7adc3a67ad2efd196145687 and 9f535729159baf467c3bd8dc7ec017a40289a12c with pull request #186 by @keszybz, I've refrained myself from updating the package in Debian, since I wasn't sure that the changes were correct.

A few weeks ago I took some time to have a small discussion with Debian's cross-builds folks about my concerns, and they said that no, the pkg-config and CMake files should **not** be installed in the arch-independent directories, because xbyak cannot be _used_ on all architectures.

You can find further reasoning, and the pros and cons of each approach, in the following messages (it wasn't a long discussion):

- [D2PY9RS3B03B.2QUVDXW5ITTHP@pappacoda.it](https://lists.debian.org/msgid-search/D2PY9RS3B03B.2QUVDXW5ITTHP@pappacoda.it)
- [172104623636.3075388.12476647907814437485@localhost](https://lists.debian.org/msgid-search/172104623636.3075388.12476647907814437485@localhost)
- [D2QIP89H195M.C9HQC0DC7J7Q@pappacoda.it](https://lists.debian.org/msgid-search/D2QIP89H195M.C9HQC0DC7J7Q@pappacoda.it)
- [172111487285.3075388.7278994695474718693@localhost](https://lists.debian.org/msgid-search/172111487285.3075388.7278994695474718693@localhost)

Therefore I'm opening this issue to coordinate with @keszybz to revert the changes without causing breakage to Fedora. In short, you should have different arch-specific packages, one for x86 which installs `.pc` files in `/usr/lib`, and one for x86_64 which installs files in `/usr/lib64`.

If you think this isn't correct, please let me know! Bye :)

**Comment by herumi** [comment]
Thank you for your feedback.
@keszybz , what do you think about this?
I am not familiar with packaging so I will follow the outcome of your discussion.

**Comment by herumi** [comment]
Hi @keszybz, If there are no particular comments by the end of this month, I will revert the noted commits.

**Comment by Tachi107** [comment]
Hi @trixirt, pinging you too as you are the maintainer of the xbyak 
package on Fedora. What are your opinions on this?

**Comment by trixirt** [comment]
In the last update to 7.07 there were other issues with meson build that lead me to go back to cmake and we only build for x86_64 so I do not know if reverting this change is necessary.

**Comment by Tachi107** [comment]
Interesting, what issue have you incountered? Looking at the Git history 
of Fedora packaging, you've skipped 7.06, which is where these 
arch-independent changes got introduced in the first place. Hence the 
pull request made by @keszybz never actually changed anything for 
Fedora.

The file move might actually be the issue you've encountered, so it 
makes sense to do the revert right now. @keszybz can always re-propose 
the patch in the future (making sure that it actually lands in Fedora, 
though!).

I'll submit a pull request shortly.

**Comment by Tachi107** [comment]
Also, to avoid the issue keszybz has encountered, you should not mark 
xbyak as noarch, but should use rpm's equivalent of dpkg's "any".

**Comment by herumi** [comment]
Thanks.
