### ISSUE TITLE
CodeArray::setSize can throw when it shouldn't

### ISSUE THREAD

**Issue by whyisthisfieldhere** [herumi/xbyak#19]
Hi again, just a small issue this time:

setSize throws an error when size >= maxSize_.
However "size_ == maxSize_" is a valid state that occurs naturally as you fill an autoGrow-enabled CodeArray.

Therefore, the following valid (in my opinion) code has a small chance to fail due to setSize throwing an error:
> size_t prevPos = getSize ();
> setSize (\<some old location\>);
> \<...do stuff...\>
> setSize (prevPos); // <-- This may throw.

I think setSize should only throw if size > maxSize_ instead.

Thanks.

EDIT: Oh, and thanks for creating xbyak - it's been a great help to me.

**Comment by herumi** [comment]
Thank you for your advice. I fixed it.
https://github.com/herumi/xbyak/commit/dcf8ca01f789329aee03cd4947eacb2a80614cfa#diff-aafd8dc5d7c50d5243799e143e40ec6eL742
