### ISSUE TITLE
test_nm failing with nasm 2.16.03

### ISSUE THREAD

**Issue by Tachi107** [herumi/xbyak#191]
Hi!

Debian recently upgraded to NASM version 2.16.03, and unfortunately this broke xbyak's test_nm.sh test. I'm not sure what broke exactly, so I'll just leave the error log here:

    cxx=g++ ./test_nm.sh
    nasm(32bit)
    compile make_nm.cpp with -wall -i../ -dxbyak32
    asm
    xbyak
    compile nm_frame.cpp
    1045,1046c1045,1046
    < 86d1
    < 86c5
    ---
    > 86ca
    > 86e8
    1048c1048
    < 86f0
    ---
    > 86c6
    1053c1053
    < 6687ce
    ---
    > 6687f1
    1061c1061
    < 87f1
    ---
    > 87ce

You may find some more information in the downstream bug report: <https://bugs.debian.org/1080144>.

What is the cause of this failure?

Thanks!

**Comment by herumi** [comment]
It is because NASM has changed the bytecode output of xchg (bytecode execution is not affected).
Xbyak 7.07.1 follows the new behavior of NASM to pass the tests.
https://github.com/herumi/xbyak/blob/master/doc/changelog.md

**Comment by Tachi107** [comment]
Thanks for the quick reply! This is indeed fixed when upgrading to the new release. Sorry for the noise!
