### ISSUE TITLE
AVX10.2 support

### ISSUE THREAD

**Issue by busykai** [herumi/xbyak#192]
Hello @herumi;

now that [AVX10.2 specification](https://www.intel.com/content/www/us/en/content-details/828965/intel-advanced-vector-extensions-10-2-intel-avx10-2-architecture-specification.html) as well as [SDE version which supports AVX10.2](https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html) are released,  could we hope for support for AVX10.2? Do you have plans to work on it?

**Comment by herumi** [comment]
I've already skimmed through that PDF, but it has too many pages.
I will support them little by little.
Is there a diff list of really new instructions for AVX10.2 from AVX-512?
For example, AVX10 NEW INSTRUCTION FORMS has vaddpd, but that is the same as an existing instruction, right?

By the way, Intel is a heavy user of Xbyak (thank you), but would your company be interested in sponsoring my contributions?
For example, Xbyak is received Google Open Source Peer Bonus Awards 2024.
https://opensource.googleblog.com/2024/06/google-open-source-peer-bonus-program-first-group-2024-recipients.html .

**Comment by busykai** [comment]
Some of the instruction that used to be "extensions" are brought in under 10.2 umbrella, it is generally part of AVX10 strategy: simplify capability detection. So instead of checking for AVX512VL and AVX512F, one would just check for AVX10.2 or higher. This was done starting AVX10.1 (which was all existing instructions). So yes, some of the instructions mentioned in the AVX10.2 spec are existing instructions.

> By the way, Intel is a heavy user of Xbyak (thank you), but would your company be interested in sponsoring my contributions?

I am an employee and cannot speak on behalf of the company, nor I can make these decisions. What I *can* do is to ask around to see what can be done. Your project provides significant value to the area I am working on (so, thank *you*!).

**Comment by herumi** [comment]
>What I can do is to ask around to see what can be done. Your project provides significant value to the area I am working on (so, thank you!).

Thank you very much. That will be sufficient.

**Comment by herumi** [comment]
@busykai
I've started working on AVX10.2 support, but are there any specific instruction sets that would be particularly beneficial to implement first?

**Comment by herumi** [comment]
The latest version, [v7.20](https://github.com/herumi/xbyak/releases/tag/v7.20), fully supported AVX10.2.
Could you try it?

**Comment by busykai** [comment]
Thank you! Will try to do it the next week. This is great!

I'm closing this issue since this is done!!!

**Comment by herumi** [comment]
@busykai 
I have one remark.
After Xbyak v7.20 was released, the AVX10.2 rev. 2 specification was updated.
This update fixes the encoding of some mnemonics such as vcomx*.
I have already implemented these changes in [the dev branch](https://github.com/herumi/xbyak/commit/c5704a21d910b5d59023afb3b6ed13eca04e65ab) to comply with the new specification.
However, since Intel XED hasn't been updated yet, I cannot verify the correctness of these changes.
Would you be able to verify these modifications? If so, I can merge them into the master branch.
