### ISSUE TITLE
Add template overload for the call function

### ISSUE THREAD

**Issue by randomstuff** [herumi/xbyak#23]
When passing a function pointer to `call`, the compiler complains on implicit conversion to `void*`, it could be fixed (when vararg templates are available) by adding an overloaded function using vararg template:

~~~c++
template<typename Result, typename... Values>
void call(Result(*addr)(Values...)) { opJmpAbs((const void*)addr, T_NEAR, 0, B11101000); }
~~~

**Comment by herumi** [comment]
Thank you for your request.
I support it. https://github.com/herumi/xbyak/commit/1e208fd20225441f9ed02c7470335c731d958ebb

**Comment by randomstuff** [comment]
Great \o/
