### ISSUE TITLE
different addresses are equal

### ISSUE THREAD

**Issue by inolen** [herumi/xbyak#24]
I had some code that was doing something to the effect of:

```
if (result_operand != arg0_operand) {
  mov(result_operand, arg0_operand);
}
```

However, that broke down when result and arg0 were instances of `Xbyak::Address` as the equality operator overload in `Xbyak::Operator` returns true for different displacements.

It seems the `Xbyak::Address::disp_` and `Xbyak::Operator::idx_` fields could be merged into a single field to fix this somewhat sanely.

**Comment by herumi** [comment]
Thank you. I fixed it. https://github.com/herumi/xbyak/commit/93aae57298703ad4525abbfbfa5ee4be048d3c3d

>It seems the Xbyak::Address::disp_ and Xbyak::Operator::idx_ fields could be merged into a single field to fix this somewhat sanely.

The current code is very dirty. I'll refactor it later.

**Comment by skmp** [comment]
Have I mentioned I love you? No? Well I love you! Thanks for being so AWESOME :3

... from earlier today ...
![xbyak-love](https://cloud.githubusercontent.com/assets/393266/9158567/37503946-3f19-11e5-95bf-61f18aee0526.png)

**Comment by inolen** [comment]
Thanks a ton @herumi! Just updated and verified it's fixed.
