### ISSUE TITLE
Silent truncation of size_t to uint32 in mov (<mem>, <size_t>) case

### ISSUE THREAD

**Issue by whyisthisfieldhere** [herumi/xbyak#25]
Hi.

A small issue I noticed - "void mov(const Operand& op, size_t imm)", in the case where "op.isMEM()", the size_t is cast to uint32, silently truncating it.
It'd be great if this would throw an exception if the value doesn't fit in an int32 instead (like I see some other places in the code already do).

**Comment by herumi** [comment]
Thank you for your advice.
How about https://github.com/herumi/xbyak/commit/f03bbc298d20c4831b7bfb23ea9378b84349a9ea ?

**Comment by whyisthisfieldhere** [comment]
Thank you for taking a look.
I'm afraid it's not quite complete, though:
mov (qword[rbx], 0xf2345678);
The above will not throw an error and will become:
mov     qword ptr [rbx],0FFFFFFFFF2345678h 
Of course, mov (dword[rbx], 0xf2345678); (dword instead of qword) should still be allowed.

**Comment by herumi** [comment]
Thank you for your advice again.
I fixed it. https://github.com/herumi/xbyak/compare/93aae57...b0bf808

**Comment by whyisthisfieldhere** [comment]
Thanks! It works great.
