### ISSUE TITLE
RIP-relative addressing with labels - issues with opcodes that have immediates

### ISSUE THREAD

**Issue by whyisthisfieldhere** [herumi/xbyak#26]
Hi,

Sorry for not catching this in the "RIP-relative addressing with labels" issue but it seems like the feature doesn't work correctly for opcodes that have an extra immediate after the modrm data (like cmpss, pshufd, test and many others).

The following testcase demonstrates it (check the resulting assembly):

        Xbyak::Label label;
        cmpss (xmm0, ptr[rip + label], 0);
        test (dword[rip + label], 33);
        bt (dword[rip + label ], 3);
        vblendpd (xmm0, dword[rip + label], 3);
        vpalignr (xmm0, qword[rip + label], 4);
        vextractf128 (dword[rip + label], ymm3, 12);
        vperm2i128 (ymm0, ymm1, qword[rip + label], 13);
        vcvtps2ph (ptr[rip + label], xmm2, 44);
        mov (dword[rip + label], 0x1234);
        shl (dword[rip + label], 3);
        shr (dword[rip + label], 1);
        shld (dword[rip + label], rax, 3);
        imul (rax, qword[rip + label], 21);
        rorx (rax, qword[rip + label], 21);
        ret ();

        L (label);
        dq (0x123456789abcdef0);
(Note: some of these write to ptr[rip + label], which I'm not sure of the legality of)

I don't see any nice fix for this, but I've prepared a rather cumbersome fix that adds optional arguments such as "int imm = NONE" and "int endOffset = 0" to handle this case, in case it helps:
https://gist.github.com/whyisthisfieldhere/3bcf044bcd06a2c474fd

What do you think?
I'd understand if you'd prefer to remove the feature if you don't consider it useful enough.

**Comment by herumi** [comment]
Thank you for your useful patch. I'm reading it now. Could you wait for a moment?

**Comment by whyisthisfieldhere** [comment]
Of course, no problem.

**Comment by herumi** [comment]
I merged your excellent patch and fixed my bug.
https://github.com/herumi/xbyak/compare/master...fi_rip_imm
There is a better way, I think it later.

**Comment by whyisthisfieldhere** [comment]
Thank you,
