### ISSUE TITLE
Support for segment registers

### ISSUE THREAD

**Issue by AlexAltea** [herumi/xbyak#28]
This feature is missing and it would be extremely convenient for me and maybe others as well. Are there any plans to implement it? If not, could you please give some guidelines about how would you like such a thing to be integrated into Xbyak? Thank you very much. :-)

**Comment by AlexAltea** [comment]
I was thinking about having a `class SegmentReg : class Reg` type for the members `cs`,`ds`,`ss`,`es`,`fs`,`gs` and extending `RegExp` to allow following expressions:

```
(ptr|dword|word|byte) [(cs|ds|ss|es|fs|gs) | base + index * (1|2|4|8) + displacement]
```

Such that, for example, following expression were possible:
```c++
mov(ecx, ptr[rax]);
mov(ecx, ptr[fs | rax]);
mov(ebx, ptr[gs | rax + rcx*4]);
mov(fs, rax);
```

This matches more or less the Intel syntax.

**Comment by herumi** [comment]
Thank you for your suggestion, but it is difficult to extend Addressing to support segment registers.

How about the following extension?

add method cs(), ds(), ... to Xbyak::CodeGenerator;
```
cs() { db(0x2e); }
ds() { db(0x3e); }
...
```
```
mov(ecx, ptr[rax]);
fs(); mov(ecx, ptr[rax]);
gs(); mov(ebx, ptr[rax + rcx*4]);
```
It is necessary for `mov` to support segment registers.

**Comment by AlexAltea** [comment]
True, that's a simpler workaround. I guess I will do that (for now). Thanks for the tip! :-)

**Comment by herumi** [comment]
https://github.com/herumi/xbyak/releases/tag/v4.87 supports the following codes.
```
putSeg(fs); mov(eax, ptr [ecx]);
mov(cs, ax);
push(ds);
```
Could you try it?

**Comment by AlexAltea** [comment]
I've tried it and it works perfectly. Thank you very much for your support and congratulations for this great library. I'm closing this issue. :-)
