### ISSUE TITLE
Some opcodes taking Reg32e despite having 16-bit variations

### ISSUE THREAD

**Issue by whyisthisfieldhere** [herumi/xbyak#29]
Hi Herumi,

A minor issue I noticed:
Some opcodes take a "Reg32e" as a parameter, despite the Intel x86/x64 docs saying that a 16-bit register is also allowed for them. (An 8-bit register isn't, though).

The opcodes are lea and cmov*

**Comment by herumi** [comment]
Thank you for your pointing out. I'll check it later.

**Comment by herumi** [comment]
I fixed it.
