### ISSUE TITLE
Support for ptr[rip + label + 1234] addressing.

### ISSUE THREAD

**Issue by kupix** [herumi/xbyak#31]
I am trying to replicate code that reads from a data section label plus an offset. In YASM code looks like this:

pat_idct32_pass1: dw ...
    ...
    lea             rax, [pat_idct32_pass1 + 352]

I am loading other data in xbyak using [rip + label] addressing. This may not be the best way but it works. I think it should be possible to do ptr[rip + pat_idct32_pass1 + 352] as above. This will not compile though (no suitable operator+). Can xbyak be made to do this? (thanks for fantastic tool btw)

**Comment by herumi** [comment]
You can write as the following.
Is it enough for you?
```
    Xbyak::Label label;
    mov(eax, ptr[rip + label]); // eax = 3
    lea(rdx, ptr[rip + label + 4]);
    add(eax, ptr[rdx]); // eax = 3 + 5
    ret();
L(label);
    dd(3);
    dd(5);
```

**Comment by kupix** [comment]
Thank you - this seems to work.
