### ISSUE TITLE
Conditional jumps w/ absolute code destinations

### ISSUE THREAD

**Issue by skmp** [herumi/xbyak#32]
Currently the code only allows Labels as conditional branch destination

eg
```
void jns(std::string label, LabelType type = T_AUTO) { opJmp(label, type, 0x79, 0x89, 0x0F); }
void jns(const Label& label, LabelType type = T_AUTO) { opJmp(label, type, 0x79, 0x89, 0x0F); }
```

For my use case I need to branch to an arbitrary destination, so I need an entry like
```
void jns(void* dst, LabelType type = T_NEAR) { opJmpAbs(dst, type, 0x79, 0x89, 0x0F); }
```

Is it possible to add this variation in the generator?

**Comment by herumi** [comment]
Thank you for your suggestion. I added the function.

**Comment by skmp** [comment]
Amazing :D Thanks :)
