### ISSUE TITLE
AVX512 support

### ISSUE THREAD

**Issue by jczaja** [herumi/xbyak#36]
Hi,

Are you working on/ planning to adding AVX512 instruction set support to xbyak?

Thanks for developing this great project. 

Regards,
Jacek

**Comment by herumi** [comment]
I'll add AVX512 in the future but not add 512-bit SIMD instructions used in Xeon Phi.
Do you want to use AVX512 soon?

**Comment by jczaja** [comment]
Yes, we are very much looking  forward to it. So far We use xbyak to get most of AVX2 instruction set, but would like to add AVX512 (including Xeon Phi instruction set).

**Comment by herumi** [comment]
I see. I'll study the format of AVX512.

**Comment by herumi** [comment]
@jczaja 
Hi, I'm sorry I kept you waiting so long.
I implmented AVX-512(not including Xeon Phi).
https://github.com/herumi/xbyak/tree/avx512#avx-512
Could you try it?

**Comment by jczaja** [comment]
@herumi Thanks for your work, as soon as I have some more time I will give it a go.
