### ISSUE TITLE
Question: how to use RIP to access "external" C structure

### ISSUE THREAD

**Issue by gregory38** [herumi/xbyak#38]
Hello,

I would like to use rip addressing to load/store from/to a C structure. I fail to understand how I can do it. As I need the `rip` value. Did I miss something, how must I write the code? Thanks you

Here a small example:
```
// In my C++ program
struct S {
    char[16] v;
} data;

// In my JIT generation
// Goal: move data.v to xmm1
```
First tentative: will really add data to rip as expected but I don't want to do that.
```
vmovdqa(xmm1, ptr [ rip + (size_t)&data]);
```

Second tentative: can't use `-` with label
```
// So you need to manually compute the address of the next instruction so something like this
Label next;
vmovdqa(xmm1, ptr [ rip - next + (size_t)&data]);
L(next);
```

Third tentative: manually compute the displacement but requires to know the size of the instruction in advance.
```
vmovdqa(xmm1, ptr [ rip + (size_t)&data - top_ - size_ - 8]);
```

**Comment by gregory38** [comment]
Actually, it would be nice to have this kind of API, so you can directly rip-addressing any structure.
```
vmovdqa(xmm1, rip_ptr[ pointer]);
```

**Comment by herumi** [comment]
I added [rip+pointer] addressing such as
```
int x;
...
mov(ptr [rip+&x], eax);
```
But Notice that Xbyak will throw exception if the offset of rip-addressing is larger than 2GiB.

**Comment by gregory38** [comment]
Thanks you very much. It works nicely
