### ISSUE TITLE
clang-cl support

### ISSUE THREAD

**Issue by freiro** [herumi/xbyak#41]
Hello,
during a recent compilation of xbyak with **clang-cl** I found the following problem:
`error LNK2019: reference to exernal symbol __xgetbv unresolved in function "public: __cdecl Xbyak::util::Cpu::Cpu(void)" (??0Cpu@util@Xbyak@@QEAA@XZ) `

clang-cl can be recognized by the programmer because it defines both _MSC_VER and \_\_clang\_\_, therefore a possible fix to this issue seems to be:
```
--- a/xbyak/xbyak_util.h
+++ b/xbyak/xbyak_util.h
@@ -49,7 +49,9 @@
 #endif

 #ifdef _MSC_VER
-extern "C" unsigned __int64 __xgetbv(int);
+       #ifndef __clang__
+               extern "C" unsigned __int64 __xgetbv(int);
+       #endif
 #endif

 namespace Xbyak { namespace util {
@@ -118,7 +120,11 @@ public:
        static inline uint64 getXfeature()
        {
 #ifdef _MSC_VER
+       #ifndef __clang__
                return __xgetbv(0);
+       #else
+               return _xgetbv(0);
+       #endif
 #else
                unsigned int eax, edx;
                // xgetvb is not support on gcc 4.2
```

This compiles without problems, not sure if this causes other problems though.
Another option might be checking for (_MSC_VER  &&   !\_\_clang\_\_) instead of only _MSC_VER.

**Comment by herumi** [comment]
Thank you for your feedback.
I tried your code, but it caused link error.
```
unresolved symbol ; unsigned __int64 __cdecl _xgetbv(unsigned int)" (?_xgetbv@@YA_KI@Z)
```
I used Visual Studio Enterprise 2015 + Clang with Microsoft CodeGen 14.0.25115.
Could you tell me the version you used?

**Comment by freiro** [comment]
I am using "clang llvm 4.0.0 (r284979)".
To make I use:
` cmake .. -TLLVM-vs2014 -G"Visual Studio 14 2015 Win64"`

Visual Studio Community 2015 v14.0.25123.00 Update 2 + clang-cl 4.0.0

I think you might be using clang-c2 (which I just found out existed) https://blogs.msdn.microsoft.com/vcblog/2015/12/04/clang-with-microsoft-codegen-in-vs-2015-update-1/.

This problems needs a bit more debugging if it doesn't work on clang-c2.
Anyway adding also "defined(\_\_llvm\_\_)" should make sure that you are explicitely targeting "clang-cl" and nothing else.

**Comment by herumi** [comment]
Thank you for your advice. I'll get and try it later.

**Comment by herumi** [comment]
I renamed __xgetbv() to _xgetbv() for clang-cl(you used).
https://github.com/herumi/xbyak/commit/d50d40878452121b3b10b0c5595f5342f5b0f02d
The current clang-c2(I used) does not support inline assembler or intrinsic function such as xgetbv and cpuid, then I gave up to support the version.

**Comment by freiro** [comment]
This seems to be working with both MSVC and Clang-cl.

Thank you 👍
