### ISSUE TITLE
[Feature Request] Allow getting Label's pointer

### ISSUE THREAD

**Issue by yuriks** [herumi/xbyak#43]
In my JIT, I compile several blocks of code that link and jump to each-other. For that I keep Labels in an array and do a L() call at the beginning of each block. However I also need to call into these blocks from external compiled code (as a function pointer). This forces me to also keep a separate array of function pointers and call getCurr() at each block together with the L(), even though the Labels already keep track of that.

So I think it would be useful to be able to get a pointer to the location represented by a Label, after compilation is done and all label locations have already been resolved.

**Comment by herumi** [comment]
Thank you for your proposal.
I add a function `Label::getAddress()`. https://github.com/herumi/xbyak/commit/86759a3bc82a5f0b6ccbea348b1076596440fe70
Is it what you want?

**Comment by yuriks** [comment]
Yes, that's perfect! Thank you so much!
