### ISSUE TITLE
PVS Studio Analyzer Errors

### ISSUE THREAD

**Issue by drillsar** [herumi/xbyak#48]
I get the following errors which show V792:

V792 xbyak.h 409 The 'isREG' function located to the right of the operator '|' will be called regardless of the value of the left operand. Perhaps, it is better to use '||'. 

V792 xbyak.h 409 The 'isExtIdx' function located to the right of the operator '|' will be called regardless of the value of the left operand. Perhaps, it is better to use '||'.

**Comment by herumi** [comment]
Thank you for your feedback.
I fixed it though it does not affect.

**Comment by drillsar** [comment]
I didn't think it would. Thanks
