### ISSUE TITLE
PVS Studio Analyzer

### ISSUE THREAD

**Issue by drillsar** [herumi/xbyak#49]
More errors came up these are considered low or medium and maybe just false positive.

V566 The integer constant is converted to pointer. Possibly an error or a bad coding style: (void *) 1 xbyak.h 752
V690 The 'Pack' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class. xbyak_util.h 309
V524 It is odd that the body of 'cmovnbe' function is fully equivalent to the body of 'cmova' function. xbyak_mnemonic.h 67
V524 It is odd that the body of 'cmovna' function is fully equivalent to the body of 'cmovbe' function. xbyak_mnemonic.h 64
V524 It is odd that the body of 'cmovz' function is fully equivalent to the body of 'cmove' function. xbyak_mnemonic.h 83
V524 It is odd that the body of 'cmovnle' function is fully equivalent to the body of 'cmovg' function. xbyak_mnemonic.h 73
V524 It is odd that the body of 'cmovnl' function is fully equivalent to the body of 'cmovge' function. xbyak_mnemonic.h 72
V524 It is odd that the body of 'cmovnge' function is fully equivalent to the body of 'cmovl' function. xbyak_mnemonic.h 71
V524 It is odd that the body of 'cmovng' function is fully equivalent to the body of 'cmovle' function. xbyak_mnemonic.h 70
V524 It is odd that the body of 'cmovnz' function is fully equivalent to the body of 'cmovne' function. xbyak_mnemonic.h 77
V524 It is odd that the body of 'cmovpo' function is fully equivalent to the body of 'cmovnp' function. xbyak_mnemonic.h 81
V524 It is odd that the body of 'cmovpe' function is fully equivalent to the body of 'cmovp' function. xbyak_mnemonic.h 80
V524 It is odd that the body of 'jnbe' function is fully equivalent to the body of 'ja' function. xbyak_mnemonic.h 350
V524 It is odd that the body of 'jna' function is fully equivalent to the body of 'jbe' function. xbyak_mnemonic.h 338
V524 It is odd that the body of 'jz' function is fully equivalent to the body of 'je' function. xbyak_mnemonic.h 414
V524 It is odd that the body of 'jnle' function is fully equivalent to the body of 'jg' function. xbyak_mnemonic.h 374
V524 It is odd that the body of 'jnl' function is fully equivalent to the body of 'jge' function. xbyak_mnemonic.h 370
V524 It is odd that the body of 'jnge' function is fully equivalent to the body of 'jl' function. xbyak_mnemonic.h 366
V524 It is odd that the body of 'jng' function is fully equivalent to the body of 'jle' function. xbyak_mnemonic.h 362
V524 It is odd that the body of 'jnz' function is fully equivalent to the body of 'jne' function. xbyak_mnemonic.h 390
V524 It is odd that the body of 'jpo' function is fully equivalent to the body of 'jnp' function. xbyak_mnemonic.h 406

**Comment by herumi** [comment]
Thank you for your information.
I have PVS Studio and know these warnings are no problem.
Could you tell me if you know how to disable these warnings?

**Comment by drillsar** [comment]
Yes at the line example error V524 is false at line 390:

at the end of line do this:
//-V524

**Comment by drillsar** [comment]
You can also leave a comment like //PVS Studio False Error

**Comment by herumi** [comment]
Thank you. I'll try it later.

**Comment by tmccaff** [comment]
I will do a pull request later

**Comment by tmccaff** [comment]
It's drillsar by the way

**Comment by herumi** [comment]
I checked all warnings. I think it requires many modification and it is too bothersome. so how about keeping the current status?

**Comment by drillsar** [comment]
I will figure it out and do a pull request if you want me to. These errors considered false correct?

**Comment by drillsar** [comment]
OK I will do that. I am going to pull from your branch on my fork and see.

Thanks

**Comment by drillsar** [comment]
Also what is this add sortline for tool I don't have that and not sure if I should add it.Can you pull a pull request to the Xenia-Project/xbyak of these changes? 

Errors that still coming up: Are these false positives?

V524 It is odd that the body of 'cmovna' function is fully equivalent to the body of 'cmovbe' function. xbyak_mnemonic.h 64
V524 It is odd that the body of 'cmovnbe' function is fully equivalent to the body of 'cmova' function. xbyak_mnemonic.h 67
V524 It is odd that the body of 'cmovng' function is fully equivalent to the body of 'cmovle' function. xbyak_mnemonic.h 70
V524 It is odd that the body of 'cmovnge' function is fully equivalent to the body of 'cmovl' function. xbyak_mnemonic.h 71
V524 It is odd that the body of 'cmovnl' function is fully equivalent to the body of 'cmovge' function. xbyak_mnemonic.h 72
V524 It is odd that the body of 'cmovnle' function is fully equivalent to the body of 'cmovg' function. xbyak_mnemonic.h 73
V524 It is odd that the body of 'cmovnz' function is fully equivalent to the body of 'cmovne' function. xbyak_mnemonic.h 77
V524 It is odd that the body of 'cmovpe' function is fully equivalent to the body of 'cmovp' function. xbyak_mnemonic.h 80
V524 It is odd that the body of 'cmovpo' function is fully equivalent to the body of 'cmovnp' function. xbyak_mnemonic.h 81
V524 It is odd that the body of 'cmovz' function is fully equivalent to the body of 'cmove' function. xbyak_mnemonic.h 83

**Comment by herumi** [comment]
The reason of thouse warnings is that cmov** and j** have some alias functions for convenience.

**Comment by herumi** [comment]
Is this ok?
https://github.com/herumi/xbyak/commit/0e9d004641af0c27085454eeba00c7e3706be6bc

**Comment by drillsar** [comment]
I will check it now.

**Comment by drillsar** [comment]
Looks good no errors now coming up

**Comment by herumi** [comment]
Thank you for quick check.
