### ISSUE TITLE
readme.txt の必要な履歴が消えている。

### ISSUE THREAD

**Issue by deepprog** [herumi/xbyak#53]
2017/07/12 ver 5.432 PVS-studioの警告を減らす
の1行分が消えています。

**Comment by herumi** [comment]
ご指摘ありがとうございます。
戻しました。https://github.com/herumi/xbyak/commit/5c914d32c07fe4b5fcd5cfcb4ee46566244e8b16

**Comment by deepprog** [comment]
確認しました。
