### ISSUE TITLE
Multi-nop align is incorrect

### ISSUE THREAD

**Issue by MerryMage** [herumi/xbyak#55]
Hi herumi,

		if (useMultiByteNop) {
			nop(size_t(getCurr()) % x);
			return;
		}

If `getCurr() % 16 == 2` this would produce a 2 byte nop. This would then result in the new `getCurr() % 16` being 4, which is incorrect.

This should be:

		if (useMultiByteNop) {
			if (size_t(getCurr()) % x == 0) return;
			nop(x - size_t(getCurr()) % x);
			return;
		}

Thanks.

**Comment by herumi** [comment]
Thank you for your quick check of my foolish bug.
I fixed it. https://github.com/herumi/xbyak/commit/d512551e914737300ba35f3c049d1b40effbe76d

**Comment by MerryMage** [comment]
Thanks very much for the fix!
