### ISSUE TITLE
[Intel MPX] BND prefix(F2h) is missing.

### ISSUE THREAD

**Issue by magurosan** [herumi/xbyak#57]
JMP/Jcc/CALL/RETの先頭にBNDプリフィックスがない場合bnd0-bnd3はゼロクリアされる仕様となっております。
現状、bndプリフィックスを出力する関数をワークアラウンドで追加して対応しておりますが、追加は可能でしょうか？
void bnd(){ db(0xF2); }

加えて、baseとindexの解釈が特殊なbndmkやbndldx/bndstx(mibエンコーディング)ではbaseとindexのレジスタの値を明確に区別する必要があるため、SIBの最適化(例： [rcx*2] ⇒ [rcx+rcx]）を抑制する必要があります。
こちらも現状は必要に応じバイトコード直打ちで対応しておりますが、ご検討くださいませ。

**Comment by herumi** [comment]
ご指摘ありがとうございます。修正がややこしくて手間取りました(また後でリファクタリングします)。
bnd()プレフィクスを追加しました。
https://github.com/herumi/xbyak/commit/d0b2fb623e2f9744a6f19fec7a2f51a8e908ea65
SIBの最適化を抑制しました。
https://github.com/herumi/xbyak/commit/e4fc9d8a9291f69ed4b49ab51297c5b06d0deecb
