### ISSUE TITLE
Add VNNI instruction support

### ISSUE THREAD

**Issue by yao-matrix** [herumi/xbyak#58]
Hi, Herumi,
  Sorry for bothering you.
  I am on a work to add INT8 VNNI instruction VPDPBUSD to xbyak to enable some VNNI test on my environment, VNNI spec is from http://kib.kiev.ua/x86docs/SDMs/319433-030.pdf.
  What I plan to do:
    I plan to add a new API in xbyak_mnemonic.h, as below:
     void vpdpbusd(const Zmm& z1, const Zmm& z2, const Operand& op) { opAVX_X_X_XM(z1, z2, op, T_66 | T_0F38 | T_EW0 | T_YMM | T_MUST_EVEX | T_N4 | T_N_VL, 0x50); }
    And I have 2 questions:
     1. This is change all needed if I don't consider unit test code completion now, anything else need I change?
     2. Is  T_N4 | T_N_VL needed or correctly used in this case?
   Thx you very much in advance for your guidance.

**Comment by herumi** [comment]
Xbyak version 5.60 already supports [vpdpbusd](https://github.com/herumi/xbyak/blob/master/xbyak/xbyak_mnemonic.h#L1796). Is it not what you need?

>2. Is T_N4 | T_N_VL needed or correctly used in this case?
No. T_N4 means `Tuple 1 Scalar for 32bit` in Table 1-12 of the intel's manual.

**Comment by yao-matrix** [comment]
Thx very much for guidance, I will update xbyak in my code base to the latest one.
