### ISSUE TITLE
namespace Xbyak::util missing some AddressFrames

### ISSUE THREAD

**Issue by MerryMage** [herumi/xbyak#59]
Hi herumi,

`AddressFrame xword, yword, zword, ptr_b, xword_b, yword_b, zword_b;` are missing from this namespace. EvexModifierRounding and EvexModifierZero are missing as well.

Thank you for your time.

**Comment by herumi** [comment]
For example, what code are you troubled with?

**Comment by MerryMage** [comment]
For a simple example, this type of code:

```
Xbyak::Address foo(size_t x) {
    using namespace Xbyak::util;
    return xword[xmm0 + x];
}
```

or other code that's outside of a child of CodeGenerator.

**Comment by herumi** [comment]
Thank you, I see.
I did not append them because I think these are not often used.
How about https://github.com/herumi/xbyak/commit/2794cde79eb71e86490061cac9622ad0067b8d15 ?

**Comment by MerryMage** [comment]
Thank you very much.
