### ISSUE TITLE
how to use vpcmpgtb

### ISSUE THREAD

**Issue by tensor-tang** [herumi/xbyak#64]
May I ask one question about how to use `void vpcmpgtb(const Xmm& x1, const Xmm& x2, const Operand& op)`.

For example:
 xmm_src with 16*s8 = [-2, 0, 3, -1, ....];
 and  I want to get xmm_dst like [0, 0, 3, 0, ...]

It can work with function `void vpcmpgtb(const Opmask& k, const Xmm& x, const Operand& op)`
```
      Opmask k;
      vpcmpgtb(k, xmm_src, xmm_zero); 
      vpmovm2b(xmm_tmp, k); 
      vandps(xmm_dst, xmm_src, xmm_tmp); 
```

But when I try 
```
      vpcmpgtb(xmm_tmp, xmm_src, xmm_zero); 
      vandps(xmm_dst, xmm_src, xmm_tmp); 
```

It throws one error:
> terminate called after throwing an instance of 'Xbyak::Error'
  what():  evex is invalid

Even though there are some other ways can do it, but I am still confuse why throw this error.

Thanks very much

**Comment by herumi** [comment]
vpcmpgtb has three encoding:
```
VPCMPGTB xmm1, xmm2, xmm3/m128 ; AVX
VPCMPGTB ymm1, ymm2, ymm3/m256 ; AVX2
VPCMPGTB k1 {k2}, xmm2, xmm3/m128 ; AVX-512
VPCMPGTB k1 {k2}, ymm2, ymm3/m256 ; AVX-512
VPCMPGTB k1 {k2}, zmm2, zmm3/m512 ; AVX-512
```
If `xmm_tmp`, `xmm_src`, `xmm_zero` show one of `xmm16`, `xmm17`, ..., `xmm31`, then
only AVX-512 type mode is available.

**Comment by tensor-tang** [comment]
Sorry for the late response, I just saw your reply.

Thanks very much.
