### ISSUE TITLE
`push(byte[edx + ecx])` dereferences a dword instead.

### ISSUE THREAD

**Issue by lvivtotoro** [herumi/xbyak#66]
(Values here are from my incident, and not made-up ones to minimize mistakes I may have made).

Suppose the dword at address `edx + ecx` is `0x01000100`, in x86 a value of `0x20001`.  
Calling `push(byte[edx + ecx])` *should* push only the first byte, so `0x01`, however Xbyak seems to emit code that pushes the entire dword onto the stack, which is unintended behavior, I think.

I may be wrong, although if I wanted to push a `dword`, I would've thought to use the `dword` `AddressFrame`, and not `byte`.

**Comment by herumi** [comment]
`push` does not have a format of `push byte [addr]`, so `push(byte[edx + ecx])` is undefined behavior.
Xbyak had better throw exception if byte is specified.
see [push](https://www.felixcloutier.com/x86/PUSH.html).

**Comment by herumi** [comment]
>Xbyak had better throw exception if byte is specified.

I fixed [it](https://github.com/herumi/xbyak/commit/71b75f653f3858403eb33d48f6346eef34b837fe).

**Comment by lvivtotoro** [comment]
Okay, thank you, I should just AND the dword in that case, since I don't see another way.
