### ISSUE TITLE
Does xbyak generate optimize code for non Intel platform like AMD?

### ISSUE THREAD

**Issue by avinashcpandey** [herumi/xbyak#72]
Does xbyak generate optimize code for latest AMD platforms?
I see it more inclined towards Intel platforms...is it the case?

**Comment by herumi** [comment]
Xbyak does not output the optimization code by itself.
Users of Xbyak need to write code to generate optimum code corresponding to the CPU (e.g., Intel or AMD).
If there is a mnemonic for only AMD that you want, it will investigate and support it.

**Comment by avinashcpandey** [comment]
Thanks @herumi for the prompt reply.
Yes I want for AMD only...can you give some pointers for how to do that?

**Comment by herumi** [comment]
The following documents are useful.

* [Instruction tables by Agner Fog](https://www.agner.org/optimize/instruction_tables.pdf)
* https://developer.amd.com/resources/developer-guides-manuals/
