### ISSUE TITLE
vcmp missing broadcast flags

### ISSUE THREAD

**Issue by jkopinsky** [herumi/xbyak#76]
The `vcmppd` and `vcmpps` instructions don't have the (respectively) `T_B64` and `T_B32` broadcast operand type flags set, even though the corresponding instructions are legal (at least on my machine/extension set).

Thanks.

**Comment by herumi** [comment]
Thank you for your report. I fixed it. https://github.com/herumi/xbyak/commit/4033564c6f006f3fb520dff1d35e32d4144e6d7a
