### ISSUE TITLE
How to visualize generated asm code for debugging?

### ISSUE THREAD

**Issue by zhangyafeikimi** [herumi/xbyak#77]
How to visualize generated asm code for debugging?

**Comment by MerryMage** [comment]
Use a disassembler. 

If you use a debugger, your debugger normally comes with one (lldb and gdb both have a `disassemble` command, see your debugger's documentation).

If you wish to disassemble your code for debugging, use a library. [zydis](https://github.com/zyantific/zydis) is a small one you could consider using.

**Comment by zhangyafeikimi** [comment]
Thank you very much. I will try it.
