### ISSUE TITLE
Instructions that were not found in the kit

### ISSUE THREAD

**Issue by UnlimitedChild** [herumi/xbyak#80]
Hello,

missing instructions, if these instructions were available, it would give extended flexibility to the engine.

```
arpl
bound
call
clac
cldemote
clflushopt
clts
clwb
cmovcc
cmps
cmpsd
encls
enter
fbld
fbstp
fclex
fcmovcc
fldenv
fnclex
fnclex*
fninit*
fnsave
fnsave*
fnstcw
fnstcw*
fnstenv
fnstenv*
fnstsw
fnstsw*
frstor
fsave
fstenv
fstsw
fxrstor
fxrstor64
fxsave
fxsave64
hlt
ibvpermilps
in
ins
insb
insd
insw
int
int n
int1
int3
into
invd
invept
invlpg
invpcid
invvpid
iret
iretd
iretq
lar
lds
leave
les
lfs
lgdt
lgs
lidt
lldt
lmsw
lods
lodsb
lodsd
lodsq
lodsw
loop
loopcc
loope
loopne
lsl
lss
ltr
mov
movdir64b
movdiri
movq
movs
movsd
nop
out
outs
outsb
outsd
outsw
pabsq
pmaxsq
pmaxuq
pminsq
pminuq
pmovsx
pmovzx
pmullq
pop
popfq
prefetchh
psraq
ptwrite
push
pushfq
rdfsbase
rdgsbase
rdpid
rdpkru
repe
repne
repnz
repz
rsm
scas
setcc
sgdt
sidt
sldt
smsw
stos
str
swapgs
syscall
sysenter
sysexit
sysret
test
tpause
ud
umonitor
umwait
vbroadcast
verr
verw
vextractf32x4
vextracti32x4
vgatherdpd
vgatherdps
vgatherqpd
vgatherqps
vmaskmov
vmcall
vmclear
vmfunc
vmlaunch
vmptrld
vmptrst
vmread
vmresume
vmwrite
vmxoff
vmxon
vpbroadcast
vpbroadcastm
vpgatherdd
vpgatherdq
vpgatherqd
vpgatherqq
vpmaskmov
vshuff32x4
vshuff64x2
vshufi32x4
vshufi64x2
wrfsbase
wrgsbase
wrpkru
xabort
xacquire
xbegin
xchg
xend
xlat
xrelease
xrstor
xrstor64
xrstors
xrstors64
xsave
xsave64
xsavec
xsavec64
xsaveopt
xsaveopt64
xsaves
xsaves64
xsetbv
xtest
xtest

ENCLS
ENCLS[EADD]
ENCLS[EAUG]
ENCLS[EBLOCK]
ENCLS[ECREATE]
ENCLS[EDBGRD]
ENCLS[EDBGWR]
ENCLS[EEXTEND]
ENCLS[EINIT]
ENCLS[ELBUC]
ENCLS[ELDBC]
ENCLS[ELDB]
ENCLS[ELDU]
ENCLS[EMODPR]
ENCLS[EMODT]
ENCLS[EPA]
ENCLS[ERDINFO]
ENCLS[EREMOVE]
ENCLS[ETRACKC]
ENCLS[ETRACK]
ENCLS[EWB]
ENCLU
ENCLU[EACCEPTCOPY]
ENCLU[EACCEPT]
ENCLU[EENTER]
ENCLU[EEXIT]
ENCLU[EGETKEY]
ENCLU[EMODPE]
ENCLU[EREPORT]
ENCLU[ERESUME]
ENCLV
ENCLV[EDECVIRTCHILD]
ENCLV[EINCVIRTCHILD]
ENCLV[ESETCONTEXT]

GETSEC[CAPABILITIES]
GETSEC[ENTERACCS]
GETSEC[EXITAC]
GETSEC[PARAMETERS]
GETSEC[SENTER]
GETSEC[SEXIT]
GETSEC[SMCTRL]
GETSEC[WAKEUP]

INVEPT
INVVPID
VMCALL
VMCLEAR
VMFUNC
VMLAUNCH
VMPTRLD
VMPTRST
VMREAD
VMRESUME
VMWRITE
VMXOFF
VMXON
```

**Comment by herumi** [comment]
Thank you for your advice.
I think xbyak is used for user application, so it does not support mnemonics for system-programming.
And Xbyak already supports call, cmps, cmpsd, fcmovcc, pmaxsq, vextractf32x4, vgatherdpd and etc. in your list.
I think again if there are especially mnemonics you want.

**Comment by UnlimitedChild** [comment]
Hi herumi, 

sad that this is the case, because it can be not only system programming, for example manual exception handling, and how are things with basic instructions like - pushfq, popfq, int, syscall, sysenter, lodsq, lods ... In any case, I would be very happy if the missing instructions were present. The project is very cool! One more question, is there a possibility in the project to output just in time code to the bin file, this is necessary for dynamic code verification, in this case, I could test the entire set of instructions for correct coding. 

Thanks for the support.  

p.s. In general, the main purpose of assembler is system programming =) One could sketch a small pdf file with a description of how to add your own instructions. That would be very nice!

**Comment by herumi** [comment]
I see, I'll support `pushfq, popfq, int, syscall, sysenter, lodsq, lods ...` at first.

>is there a possibility in the project to output just in time code to the bin file

How about saving (code.getCode(), code.getSize()) for CodeGenerator code?

**Comment by herumi** [comment]
I'm now appending some mnemonics at [dev branch](https://github.com/herumi/xbyak/tree/dev).
Please tell me high priority list if you have. And do you need mnemonics which requires level 0 privilege?

**Comment by UnlimitedChild** [comment]
Hello, 

was away these days, some instructions exist, they are simply encoded differently, for example, as SETAE r / m8 * SETBE r / m8 *, but not all, I re-checked the list ..

A list of instructions that are exactly required for daily work, priority from top to bottom ..
 
```
pushfq
popfq 
enter
leave
int 
test
syscall
sysenter
sysexit
sysret
stosq
loop
loopcc
loope
loopne
movsq
nop
pabsq
pmaxsq
pmaxuq
pminsq
pminuq
pmullq
```

> //And do you need mnemonics which requires level 0 privilege?
no, not necessarily =)

> //How about saving (code.getCode(), code.getSize()) for CodeGenerator code?
Thank you, I think this is what I need!

**Comment by herumi** [comment]
The following mnemonics are already supported.

```
pushfq
popfq 
int       ; use int_ instead of int
syscall
sysenter
sysexit
sysret
stosq
movsq
nop
pabsq
pmaxsq
pmaxuq
pminsq
pminuq
pmullq
```

The following mnemonics are old and very slow.
eg. dec ecx / jnz lp is faster than loop

Could you tell me the reason why you want to use them?

```
enter
leave

loop
loopcc
loope
loopne
```

**Comment by UnlimitedChild** [comment]
1. These instructions are often used in textbooks and examples.
2. In non-speed-critical procedures or code generators.
3. leave is often used without enter.
4. Tribute to the past =)

But in general I completely agree! =) The main goal is educational ..

**Comment by herumi** [comment]
I see. I've appended those mnemonics at [dev](https://github.com/herumi/xbyak/tree/dev).
If you have other mnemonics you want, please show me them.

**Comment by UnlimitedChild** [comment]
> you have other mnemonics you want, please show me them.

`fbld
fbstp
fclex
fldenv
fnclex
fnsave
fnstcw
fnstenv
fnstsw
frstor
fsave
fstenv
fstsw
fxrstor
fxsave
hlt
invd
invlpg
invpcid
lds - LDS/LES/LFS/LGS/LSS—Load Far Pointer
REP/REPE/REPZ/REPNE/REPNZ—Repeat String Operation Prefix
lods
`

**Comment by herumi** [comment]
hlt invd invlpg invpcid requires privilege level 0.
Do you need them really?


> //And do you need mnemonics which requires level 0 privilege?
>
>no, not necessarily =)

**Comment by UnlimitedChild** [comment]
> hlt invd invlpg invpcid require privilege level 0.
> Do you need them really?

Hello, 
no, I wrote it automatically =) Thank you so much for the work! I will test it with multifunctional code generation!

Regards
