### ISSUE TITLE
Calls to exit()

### ISSUE THREAD

**Issue by rsdubtso** [herumi/xbyak#83]
Hi Herumi, MKL-DNN has a PR (https://github.com/intel/mkl-dnn/pull/572) to, among other things, remove calls to `exit()` (https://github.com/intel/mkl-dnn/pull/572#discussion_r334127735). I see two such calls:
- `Xbyak::Error::Error()`:  https://github.com/herumi/xbyak/blob/a1e9adf22831d8070c43e83be05384be0c9a1c7e/xbyak/xbyak.h#L196-L202 In this case I think it should be possible to just add another error id enum like `ERR_UNKNOWN = ERR_INTERNAL + 1` and create an exception with this id.

- `Xbyak::StackFrame::~StackFrame()`: https://github.com/herumi/xbyak/blob/a1e9adf22831d8070c43e83be05384be0c9a1c7e/xbyak/xbyak_util.h#L704-L713 In this case I think it shoudl be OK to rethrow the exception.

I want to get your perspective on this.

**Comment by herumi** [comment]
I see. I've removed it. https://github.com/herumi/xbyak/commit/f32836da6f64d87856c8706aea2b647ef198d8c6

**Comment by rsdubtso** [comment]
That was quick! Thanks!
