### ISSUE TITLE
32-bit offset in XBYAK is not enough

### ISSUE THREAD

**Issue by grygielski** [herumi/xbyak#88]
Hi @herumi, I have following problem. I've got a code that works just fine but when data size gets too big I receive `Xbyak::Error: offset is too big`. As far as I understand it's because of limitation on 32-bit offset. Is there any workaround for that? Snippet of my actual function:
```c++
constexpr int max_num_regs = 7;
std::vector<int> groups(num_groups, max_num_regs);
// num_groups ~ size of data

...

const Xbyak::Reg64 reg_ptr_grad_i{r10};
const Xbyak::Reg64 reg_ptr_param_i{r14};
const Xbyak::Reg64 reg_ptr_out_i{r15};

...

size_t w_offset = 0;
for (int num_regs : groups) {
  size_t inner_offfset = w_offset;
  for (int reg_i = 0; reg_i < num_regs; ++reg_i) {
    vmovups(Xbyak::Ymm(reg_i), ptr[reg_ptr_grad_i + inner_offfset]); // load grad
    vmovups(Xbyak::Ymm(reg_i + num_regs), ptr[reg_ptr_param_i + inner_offfset]); // load param

    vmulps(Xbyak::Ymm(reg_i), Xbyak::Ymm(reg_i), ymm_lr); // multiply grad with lr
    vsubps(Xbyak::Ymm(reg_i + num_regs), Xbyak::Ymm(reg_i + num_regs), Xbyak::Ymm(reg_i)); // substract result from param

    vmovups(ptr[reg_ptr_out_i + inner_offfset], Xbyak::Ymm(reg_i + num_regs)); // save out

    inner_offfset += block_size;
  }
  w_offset += (block_size * num_regs);
}
```
If it's not enough I can paste my whole code here.

**Comment by rsdubtso** [comment]
This is x86_64 ISA limitation. Offsets in SIB (stride,index,base) encodings are signed 32-bit integers. There is absolute addressing mode that does not have SIB. The only workaround for that is to use an extra register or move the base register.

**Comment by grygielski** [comment]
@rsdubtso Could you give me an example of absolute addressing that I can use here? I'm trying to learn a bit about 64bit assembly with XBYAK but got stuck at that. I would be grateful.

**Comment by herumi** [comment]
>Could you give me an example of absolute addressing that I can use here?

Here is a sample of accessing a global variable.
```
#include <stdio.h>
#include <xbyak/xbyak.h>

int g_x = 3;

struct Code : Xbyak::CodeGenerator {
  Code()
  {
    mov(rax, (size_t)&g_x); // you can use 64-bit offset
    mov(dword[rax], 5);
    ret();
  }
};

int main()
{
  Code c;
  auto f = c.getCode<void(*)()>();
  printf("g_x = %d\n", g_x);
  f();
  printf("g_x = %d\n", g_x);
}
```

**Comment by grygielski** [comment]
Well, I actually did it earlier almost exactly the same but haven't noticed that it works because of another `Xbyak::error Offset is too big` error. Now I have problems with jumps to label. It seems that code is getting too big to handle such jump. Am I correct? Maybe could you propose possible solution/workaround for that?
**Updated snippet of code:**
```c++
Xbyak::Label l_next_row;
L(l_next_row);
{
  mov(reg_row, qword[reg_ptr_rows_i]);
  mov(rax, width_size);
  mul(reg_row);
  mov(reg_row, rax);

  mov(reg_ptr_param_i, param_param);
  mov(reg_ptr_out_i, param_out);
  add(reg_ptr_param_i, reg_row);
  add(reg_ptr_out_i, reg_row);

  for (int num_regs : groups) {
    for (int reg_i = 0; reg_i < num_regs; ++reg_i) {
      vmovups(Xbyak::Ymm(reg_i), ptr[reg_ptr_grad_i]); // load grad
      vmovups(Xbyak::Ymm(reg_i + num_regs), ptr[reg_ptr_param_i]); // load param

      vmulps(Xbyak::Ymm(reg_i), Xbyak::Ymm(reg_i), ymm_lr); // multiply grad with lr
      vsubps(Xbyak::Ymm(reg_i + num_regs), Xbyak::Ymm(reg_i + num_regs), Xbyak::Ymm(reg_i)); // substract result from param

      vmovups(ptr[reg_ptr_out_i], Xbyak::Ymm(reg_i + num_regs)); // save out

      add(reg_ptr_grad_i, block_size);
      add(reg_ptr_param_i, block_size);
      add(reg_ptr_out_i, block_size);
    }
  }
  add(reg_ptr_grad_i, width_size);
  add(reg_ptr_rows_i, sizeof(int64_t));
  cmp(reg_ptr_rows_i, reg_rows_size_in_byte);
  jl(l_next_row, T_NEAR); // Here program crashes for large data sizes (even if condition isn't satisfied)
}
```

**Comment by herumi** [comment]
How large is `groups`?

**Comment by grygielski** [comment]
For large data (that causes crash) it's e.g. `groups.size() = 26785715`. This is `std::vector<int>` filled with `7`s

**Comment by herumi** [comment]
It's too large. It will generate very large code and spill code cache. So I think that it is better to make an inner loop to reduce code size.

**Comment by grygielski** [comment]
By inner loop you mean label/jump based loop instead of `for` with groups or something else?

**Comment by herumi** [comment]
Yes. I think you should replace `for (int num_regs : groups) {` with `label/jump`.

**Comment by grygielski** [comment]
Thanks a lot, I'll try that tomorrow

**Comment by grygielski** [comment]
Now everything works perfectly, thank you so much for help :+1:
