### ISSUE TITLE
kmov broken when using Reg64

### ISSUE THREAD

**Issue by kaczorrrro** [herumi/xbyak#90]
I'm trying to call `kmovw(Opmask, Register);`
When using Reg64 class wrong overload of kmovw gets selected. Minimal failing example posted below.

```
#define XBYAK_NO_OP_NAMES
#include <xbyak/xbyak.h>
#include <iostream>

struct Gen : public Xbyak::CodeGenerator {
  Gen() {

    Xbyak::Reg64 tmp = rsi;
    int mask = 0b1010'1010'1010'1010;
    mov(tmp, mask);

    kmovw(k1, tmp);
//    kmovw(k1, (Xbyak::Reg32&)tmp);
// cast to Xbyak::Reg32 forces proper overload

    vxorps(zmm0, zmm0, zmm0);
    vmovups(ptr[rdi], zmm0 | k1);
    ret();
  }
};

int main() {
  float data[16]      = {1,1,1,1, 1,1,1,1, 1,1,1,1, 1,1,1,1, };
  float expected [16] = {1,0,1,0, 1,0,1,0, 1,0,1,0, 1,0,1,0, };
  Gen g;
  g.getCode<void(*)(float*)>()(&data[0]);
  for (int i = 0; i < 16; i++)
    if (data[i] != expected[i])
      std::cout << "At " << i << " got " << data[i] << " expected " << expected[i] << std::endl;
}
```
Selected overload used opcode 90 which is invalid in this case.
I'd expect opcode 92 to be emitted or an error.

**Comment by rsdubtso** [comment]
While this clearly is a bug (the generated instruction is `kmovw k1, k6` which means that Xbyak interprets `rsi` which has index=6 as a mask register), I would actually expect Xbyak to complain about a 64-bit register being passed to `kmovw` which only operates on 32-bit GPRs.

**Comment by MerryMage** [comment]
instead of a cast, `kmovw(k1, tmp.cvt32());` can be used.

**Comment by kaczorrrro** [comment]
Hey, thanks for quick response. I've switched to `tmp.cvt32()` given that my cast was illegal. I'm hoping this one will be resolved so no one else has this issue in future :)

**Comment by herumi** [comment]
Thank you for your feedback. I'll fix it. Please wait for a moment.

**Comment by herumi** [comment]
You can use `Xbyak::Reg32 tmp = esi;` instead of `tmp.cvt32()`.

**Comment by herumi** [comment]
I fixed it at https://github.com/herumi/xbyak/releases/tag/v5.90 , so now `kmovw(k1, rsi);` throws an exception, then please use `kmovw(k1, esi)`.
