### ISSUE TITLE
bazel support

### ISSUE THREAD

**Issue by mobileink** [herumi/xbyak#92]
Hello.  Thank you for developing xbyak and making it available as open source.

I have forked this repo to https://github.com/mobileink/xbyak in order to add support for the [Bazel](https://bazel.build/) build system.  This involves no changes to the source, only the addtion of some files.  There are many benefits to using bazel; the main thing I'm interested in is cross-platform builds.  Also, I'm doing the same thing for ate-pairing; the ultimate goal being to bazelize libsnark.

Naturally it would be best to integrate bazel support in your repo; if you are open to this let me know and I will prepare a pull request.

Sincerely

Gregg Reynolds

**Comment by herumi** [comment]
Thank you for the information.
But xbyak is header only, so I think that it is easy to copy xbyak into ate-pairing. How do you think about?

**Comment by herumi** [comment]
I close this issue because I'll not support bazel now.
